### ISSUE TITLE
获取所有记录问题

### ISSUE THREAD

**Issue by Eddie-he** [decker502/dnspod-go#5]
client.Domains.ListRecords("deusdi.com","news")这个如何获取所有域名下的记录？
![image](https://user-images.githubusercontent.com/3214491/38786319-c03edc90-4159-11e8-87af-f5fd1239ec28.png)

**Comment by Eddie-he** [comment]
我看了下dnspod的接口是可选参数，但是我看你源码里有domain_id的信息，这个运行报错。
![image](https://user-images.githubusercontent.com/3214491/38791159-ac8ad072-4178-11e8-8deb-923259b5fbf1.png)
![image](https://user-images.githubusercontent.com/3214491/38791181-d4e9f46c-4178-11e8-82ac-78ca53589608.png)

**Comment by Eddie-he** [comment]
我看了下post数据，domain_id提交了domain的原因
![image](https://user-images.githubusercontent.com/3214491/38798864-6b73cbee-4195-11e8-8102-9510b1c1df0f.png)

**Comment by decker502** [comment]
是参数名没起好，应该传入 domain id ，已经改好，欢迎测试。如果需要参数名的调用方式，也欢迎提交代码，多谢！

**Comment by Eddie-he** [comment]
id和domain都可以吧，我看dnspod接口是这样的，我目前直接改了domain，主要是通过api查询记录生成exec文件，做备份。

**Comment by Eddie-he** [comment]
可以关闭这个问题了，哈哈～

**Comment by decker502** [comment]
@Eddie-he 都可以, 这两个参数都是可选值
