### ISSUE TITLE
Domain ID 改为 json.Number 后和lego不兼容

### ISSUE THREAD

**Issue by mukaiu** [decker502/dnspod-go#8]
建议是否调整后去？

https://github.com/go-acme/lego/issues/827

**Comment by colachg** [comment]
我也碰到了这个问题，在本地将 `if hostedZone.ID == 0` 换成 `if hostedZone.ID == "0"` 　临时解决了下。:(

**Comment by mukaiu** [comment]
@colachg 我这边通过go mod使用上一版本

**Comment by decker502** [comment]
新的 dnspod-go 版本兼容性更好，建议引用到旧版本的代码使用版本控制来解决会更好，谢谢
