### ISSUE TITLE
json fail

### ISSUE THREAD

**Issue by lscgzwd** [decker502/dnspod-go#9]
acme: error cleaning up: API call failed: json: cannot unmarshal string into Go struct field DomainInfo.info.mine_total of type int

**Comment by 0x01toby** [comment]
错误提示：
![image](https://user-images.githubusercontent.com/17560081/71983235-47709b00-3261-11ea-915b-e0fb0acf4b02.png)

dnspod官方api接口：
![image](https://user-images.githubusercontent.com/17560081/71983287-6838f080-3261-11ea-86aa-6fcd100faf9b.png)

![image](https://user-images.githubusercontent.com/17560081/71983276-61aa7900-3261-11ea-9e57-58202ea067ba.png)

作者struct定义：
![image](https://user-images.githubusercontent.com/17560081/71983309-7424b280-3261-11ea-9e06-0fe42a604f93.png)

麻烦修复一下。

**Comment by decker502** [comment]
这个pr应该修复了此问题，谢谢反馈
#10
